#!/usr/bin/env bash

function initStackDir(){
    rm -rf /tmp/$TMUX_PANE-stack
    mkdir /tmp/$TMUX_PANE-stack
    stackdir=/tmp/$TMUX_PANE-stack
    #echo created $stackdir >&2
}

function addEntriesToStack(){
    count=0

    for arg in "$@"
    do
        echo $arg >> $stackdir/item.$((++count))
    done
}
